//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLBaseTabelViewCell.h"

#import "QLTopicInfoLiteItemViewDelegate.h"

@class NSString, QLTopicInfoLiteComposite, QLTopicInfoLiteItemView, UIColor;

@interface QLTopicInfoLiteItemCell : QLBaseTabelViewCell <QLTopicInfoLiteItemViewDelegate>
{
    UIColor *_themeColor;
    id <QLTopicInfoLiteItemCellDelegate> _viewCtlDelegate;
    QLTopicInfoLiteComposite *_topicCom;
    QLTopicInfoLiteItemView *_leftView;
    QLTopicInfoLiteItemView *_rightView;
}

@property(retain, nonatomic) QLTopicInfoLiteItemView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) QLTopicInfoLiteItemView *leftView; // @synthesize leftView=_leftView;
@property(retain, nonatomic) QLTopicInfoLiteComposite *topicCom; // @synthesize topicCom=_topicCom;
@property(nonatomic) __weak id <QLTopicInfoLiteItemCellDelegate> viewCtlDelegate; // @synthesize viewCtlDelegate=_viewCtlDelegate;
@property(retain, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor;
- (void).cxx_destruct;
- (void)reportShowUp;
- (void)QLTopicInfoLiteItemView:(id)arg1 tapAction:(id)arg2;
- (void)layoutSubviews;
- (void)setObject:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

