//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _DeallocTaskModel : NSObject
{
    struct _opaque_pthread_mutex_t _lock;
    struct __CFDictionary *_tasksDict;
    id _target;
}

@property(nonatomic) id target; // @synthesize target=_target;
- (void)dealloc;
- (void)removeAllTask;
- (_Bool)removeTaskWithIdentifier:(unsigned long long)arg1;
- (unsigned long long)addTask:(CDUnknownBlockType)arg1;
- (id)initWithTarget:(id)arg1;

@end

