//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAAnimation.h"

@interface CAAnimation (WAnimation)
+ (id)bounce_AnimationRepeatTimes:(float)arg1 durTimes:(float)arg2 forObj:(id)arg3;
+ (id)shake_AnimationRepeatTimes:(float)arg1 durTimes:(float)arg2 forObj:(id)arg3;
+ (id)scaleFrom:(double)arg1 toScale:(double)arg2 durTimes:(float)arg3 rep:(float)arg4;
+ (id)rotation:(float)arg1 degree:(float)arg2 direction:(unsigned long long)arg3 repeatCount:(int)arg4;
+ (id)opacityTimes_Animation:(float)arg1 durTimes:(float)arg2;
+ (id)opacityForever_Animation:(float)arg1;
@end

