//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAAnimation.h"

@interface CAAnimation (EasingEquations)
+ (void)addAnimationToLayer:(id)arg1 withKeyPath:(id)arg2 duration:(double)arg3 from:(double)arg4 to:(double)arg5 easingFunction:(long long)arg6;
+ (void)addAnimationToLayer:(id)arg1 withKeyPath:(id)arg2 duration:(double)arg3 to:(double)arg4 easingFunction:(long long)arg5;
+ (id)animationWithKeyPath:(id)arg1 duration:(double)arg2 from:(double)arg3 to:(double)arg4 easingFunction:(long long)arg5;
+ (void)addAnimationToLayer:(id)arg1 duration:(double)arg2 transform:(struct CATransform3D)arg3 easingFunction:(long long)arg4;
+ (id)transformAnimationWithDuration:(double)arg1 from:(struct CATransform3D)arg2 to:(struct CATransform3D)arg3 easingFunction:(long long)arg4;
+ (CDUnknownBlockType)blockForCAAnimationEasingFunction:(long long)arg1;
@end

