//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface CALayer (Frame)
@property struct CGPoint center;
@property double width;
@property double height;
@property double centerY;
@property double centerX;
@property double right;
@property double left;
@property double bottom;
@property double top;
@end

