//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAMediaTimingFunction.h"

@interface CAMediaTimingFunction (AdditionalEquations)
+ (id)easeInOutBack;
+ (id)easeOutBack;
+ (id)easeInBack;
+ (id)easeInOutSine;
+ (id)easeOutSine;
+ (id)easeInSine;
+ (id)easeInOutQuint;
+ (id)easeOutQuint;
+ (id)easeInQuint;
+ (id)easeInOutQuart;
+ (id)easeOutQuart;
+ (id)easeInQuart;
+ (id)easeInOutQuad;
+ (id)easeOutQuad;
+ (id)easeInQuad;
+ (id)easeInOutExpo;
+ (id)easeOutExpo;
+ (id)easeInExpo;
+ (id)easeInOutCubic;
+ (id)easeOutCubic;
+ (id)easeInCubic;
+ (id)easeInOutCirc;
+ (id)easeOutCirc;
+ (id)easeInCirc;
@end

