//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NSObject<OS_dispatch_source>;

@interface CountDownManager : NSObject
{
    NSObject<OS_dispatch_source> *_timer;
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)dealloc;
- (void)destoryTimer;
- (id)getNowyyyymmdd;
- (void)countDownWithStratTimeStamp:(long long)arg1 finishTimeStamp:(long long)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (id)dateWithLongLong:(long long)arg1;
- (void)countDownWithPER_SECBlock:(CDUnknownBlockType)arg1;
- (void)countDownWithStratDate:(id)arg1 finishDate:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (id)init;

@end

