//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class GHConsoleRootViewController;

@interface GHConsoleWindow : UIWindow
{
    GHConsoleRootViewController *_consoleRootViewController;
}

+ (id)consoleWindow;
@property(retain, nonatomic) GHConsoleRootViewController *consoleRootViewController; // @synthesize consoleRootViewController=_consoleRootViewController;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)minimize;
- (void)maxmize;

@end

