//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GifDecoder : NSObject
{
    struct CGImageSource *_source;
    unsigned long long _frameCount;
    unsigned long long _loopCount;
}

+ (id)decoderWithData:(id)arg1;
+ (id)decoderWithGIFNamed:(id)arg1;
@property(nonatomic) unsigned long long loopCount; // @synthesize loopCount=_loopCount;
- (id)gifImage;
- (id)contentImages;
- (id)frameAtIndex:(unsigned long long)arg1;
- (void)_decoderPrepareWithData:(id)arg1;
- (void)dealloc;

@end

