//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface GifFrame : NSObject
{
    unsigned long long _index;
    double _duration;
    UIImage *_image;
}

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
- (void).cxx_destruct;

@end

