//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface KKLog : NSObject
{
}

+ (id)platformString;
+ (id)platform;
+ (id)getLogTime:(id)arg1;
+ (void)logE:(id)arg1;
+ (void)logW:(id)arg1;
+ (void)logI:(id)arg1;
+ (void)logD:(id)arg1;
+ (void)logV:(id)arg1;
+ (void)logLevel:(int)arg1 LogInfo:(id)arg2;
+ (void)logCrash:(id)arg1;
+ (void)logvLevel:(int)arg1 Format:(id)arg2 VaList:(struct __va_list_tag [1])arg3;
+ (void)setLogLevel:(int)arg1;
+ (void)logIntial;
+ (id)KKLogFormatPrefix:(int)arg1;
+ (id)KKStringFromLogLevel:(int)arg1;
+ (id)nowBeijingTime;

@end

