//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface LCMemoryCache : NSObject
{
    int _current;
    NSMutableDictionary *_cache;
}

@property(retain, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
@property(nonatomic) int current; // @synthesize current=_current;
- (void).cxx_destruct;
- (void)clear;
- (void)setKey:(id)arg1 value:(id)arg2;
- (id)get:(id)arg1;
- (id)init;

@end

