//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (Plist)
+ (id)arrayWithPlistString:(id)arg1;
+ (id)arrayWithPlistData:(id)arg1;
- (id)plistString;
- (id)plistData;
@end

