//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (SafeAccess)
- (double)doubleWithIndex:(unsigned long long)arg1;
- (float)floatWithIndex:(unsigned long long)arg1;
- (short)shortWithIndex:(unsigned long long)arg1;
- (BOOL)charWithIndex:(unsigned long long)arg1;
- (long long)int64WithIndex:(unsigned long long)arg1;
- (int)int32WithIndex:(unsigned long long)arg1;
- (short)int16WithIndex:(unsigned long long)arg1;
- (_Bool)boolWithIndex:(unsigned long long)arg1;
- (unsigned long long)unsignedIntegerWithIndex:(unsigned long long)arg1;
- (long long)integerWithIndex:(unsigned long long)arg1;
- (id)dictionaryWithIndex:(unsigned long long)arg1;
- (id)arrayWithIndex:(unsigned long long)arg1;
- (id)numberWithIndex:(unsigned long long)arg1;
- (id)stringWithIndex:(unsigned long long)arg1;
- (id)objectWithIndex:(unsigned long long)arg1;
- (id)randomObject;
@end

