//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (AppInfo)
+ (id)localizedDisplayName;
+ (id)version;
+ (id)bundleIdentifier;
+ (id)bundleName;
- (id)appIcon;
- (id)appIconPath;
@end

