//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Formatter)
+ (id)dateWithYear:(long long)arg1 month:(unsigned long long)arg2 day:(unsigned long long)arg3;
+ (id)dateWithSecondsFromNow:(long long)arg1;
+ (id)currentDateStringWithFormat:(id)arg1;
+ (id)formatterWithoutDate;
+ (id)formatterWithoutTime;
+ (id)formatter;
- (id)dateWithFormat:(id)arg1;
- (id)formatTimeWithTimeZone:(id)arg1;
- (id)formatWithTimeZoneOffsetWithoutDate:(double)arg1;
- (id)formatWithLocalTimeWithoutDate;
- (id)formatWithUTCWithoutDate;
- (id)formatWithTimeZoneWithoutTime:(id)arg1;
- (id)formatWithTimeZoneOffsetWithoutTime:(double)arg1;
- (id)formatWithLocalTimeZoneWithoutTime;
- (id)formatWithUTCTimeZoneWithoutTime;
- (id)formatWithTimeZone:(id)arg1;
- (id)formatWithTimeZoneOffset:(double)arg1;
- (id)formatWithLocalTimeZone;
- (id)formatWithUTCTimeZone;
@end

