//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Code)
+ (id)dataWithBase64EncodedString:(id)arg1;
+ (id)dataWithHexString:(id)arg1;
- (id)jsonValueDecoded;
- (id)base64EncodedString;
- (id)hexString;
- (id)utf8String;
@end

