//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Cache)
+ (id)getDataCacheWithKey:(id)arg1;
+ (id)creatDataPathWithString:(id)arg1;
+ (id)creatMD5StringWithString:(id)arg1;
+ (id)cachePath;
- (void)saveDataCacheWithKey:(id)arg1;
@end

