//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (JKzlib)
- (_Bool)writeInflatedToFile:(id)arg1 error:(id *)arg2;
- (_Bool)jk_writeDeflatedToFile:(id)arg1 error:(id *)arg2;
- (_Bool)deflate:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (_Bool)inflate:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (id)dataByDeflatingWithError:(id *)arg1;
- (id)dataByInflatingWithError:(id *)arg1;
@end

