//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Figure)
+ (id)timeIntervalFromLastTime:(id)arg1 ToCurrentTime:(id)arg2;
+ (long long)calculateTimeFromLastTime:(id)arg1 lasTimeFormat:(id)arg2 toCurrentTime:(id)arg3 currentTimeFormat:(id)arg4;
+ (id)timeIntervalFromLastTime:(id)arg1 lastTimeFormat:(id)arg2 ToCurrentTime:(id)arg3 currentTimeFormat:(id)arg4;
+ (id)getWeekStringFromInteger:(long long)arg1;
+ (long long)getDayNumbertoDay:(id)arg1 beforDay:(id)arg2;
+ (id)stringFromDate:(id)arg1;
+ (id)dateFromString:(id)arg1;
- (id)stringWithFormat:(id)arg1;
- (id)descriptionDateString;
- (long long)getWeekWithDate;
- (long long)numberOfWeekInMoth;
- (id)standerComponents;
- (id)followingYear:(long long)arg1;
- (id)followingMonth:(long long)arg1;
- (id)followingWeek:(long long)arg1;
- (id)followingDay:(long long)arg1;
- (id)followingHour:(long long)arg1;
- (id)followingMinute:(long long)arg1;
- (id)followingSecond:(long long)arg1;
- (id)lastDayOfMonth;
- (id)firstDayOfMonth;
- (long long)weekOrdinality;
- (long long)numberOfDayInMonth;
@end

