//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@class NSDictionary, NSString;

@interface NSDate (Lunar)
+ (id)lunarToSolar:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
+ (id)solarToLunar:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
+ (id)calendarInfo:(long long)arg1 month:(long long)arg2;
@property(readonly, nonatomic) NSDictionary *lunarInfo;
@property(readonly, nonatomic) NSDictionary *calendarInfo;
@property(readonly, nonatomic) NSString *yearZodiac;
@property(readonly, nonatomic) NSString *lunarYearName;
@property(readonly, nonatomic) _Bool isLeapYear;
@property(readonly, nonatomic) _Bool isNewLunarYear;
- (int)_day;
- (int)_month;
- (int)_year;
@end

