//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@class NSString;

@interface NSDate (Show)
+ (id)chineseCalendarWithDate:(id)arg1;
+ (id)ymdHmsFormat;
+ (id)hmsFormat;
+ (id)ymdFormat;
+ (id)ymdHmsFormatWithDate:(id)arg1;
+ (id)hmsFormatWithDate:(id)arg1;
+ (id)ymdFormatWithDate:(id)arg1;
+ (id)monthStringFromDate:(id)arg1;
+ (id)weekStringFromDate:(id)arg1;
- (id)chineseCalendar;
- (id)_stringWithFormat:(id)arg1;
- (id)ymdHmsFormat;
- (id)hmsFormat;
- (id)ymdFormat;
- (id)monthString;
- (id)weekString;
@property(readonly, nonatomic) NSString *longDateString;
@property(readonly, nonatomic) NSString *longTimeString;
@property(readonly, nonatomic) NSString *longString;
@property(readonly, nonatomic) NSString *mediumDateString;
@property(readonly, nonatomic) NSString *mediumTimeString;
@property(readonly, nonatomic) NSString *mediumString;
@property(readonly, nonatomic) NSString *shortDateString;
@property(readonly, nonatomic) NSString *shortTimeString;
@property(readonly, nonatomic) NSString *shortString;
- (id)stringWithDateStyle:(unsigned long long)arg1 timeStyle:(unsigned long long)arg2;
@end

