//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDecimalNumber.h"

@interface NSDecimalNumber (Easy)
+ (id)max:(id)arg1 another:(id)arg2;
+ (id)min:(id)arg1 another:(id)arg2;
+ (id)mul:(id)arg1 another:(id)arg2;
+ (id)div:(id)arg1 another:(id)arg2;
+ (id)sub:(id)arg1 another:(id)arg2;
+ (id)add:(id)arg1 another:(id)arg2;
+ (long long)compare:(id)arg1 anotherDecimalNumber:(id)arg2;
+ (id)decimalNumber:(id)arg1 type:(long long)arg2 anotherDecimalNumber:(id)arg3 andDecimalNumberHandler:(id)arg4;
+ (id)decimalNumber:(id)arg1 roundingMode:(unsigned long long)arg2 scale:(int)arg3;
@end

