//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (XML)
- (void)convertNode:(id)arg1 withString:(id)arg2 andTag:(id)arg3;
- (id)XMLStringWithRootElement:(id)arg1 declaration:(id)arg2;
- (id)XMLStringDefaultDeclarationWithRootElement:(id)arg1;
- (id)XMLString;
@end

