//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (Block)
- (id)rejectWithBlock:(CDUnknownBlockType)arg1;
- (id)filterWithBlock:(CDUnknownBlockType)arg1;
- (id)mapWithBlock:(CDUnknownBlockType)arg1;
- (void)eachValueWithBlock:(CDUnknownBlockType)arg1;
- (void)eachKeyWithBlock:(CDUnknownBlockType)arg1;
- (void)eachWithBlock:(CDUnknownBlockType)arg1;
@end

