//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSKeyedArchiver.h"

@interface NSKeyedArchiver (Key)
+ (id)defaultPath;
+ (void)_createDirectoryForKey:(id)arg1 WithFloderPath:(id)arg2;
+ (id)_filePathForKey:(id)arg1 WithFloderPath:(id)arg2;
+ (_Bool)archiveExistsForKey:(id)arg1;
+ (_Bool)archiveExistsForKey:(id)arg1 WithFolderPath:(id)arg2;
+ (_Bool)removeArchiveForKey:(id)arg1;
+ (_Bool)removeArchiveForKey:(id)arg1 WithFolderPath:(id)arg2;
+ (_Bool)archiveRootObject:(id)arg1 forKey:(id)arg2;
+ (_Bool)archiveRootObject:(id)arg1 forKey:(id)arg2 WithFolderPath:(id)arg3;
@end

