//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSKeyedUnarchiver.h"

@interface NSKeyedUnarchiver (Key)
+ (id)defaultPath;
+ (id)_filePathForKey:(id)arg1 WithFloderPath:(id)arg2;
+ (id)unarchiveObjectForKey:(id)arg1 failure:(CDUnknownBlockType)arg2;
+ (id)unarchiveObjectForKey:(id)arg1 WithPath:(id)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)unarchiveObjectForKey:(id)arg1;
+ (id)unarchiveObjectForKey:(id)arg1 WithPath:(id)arg2;
@end

