//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutConstraint.h"

@interface NSLayoutConstraint (Refer)
+ (id)view:(id)arg1 widthToMultipleOfHeight:(double)arg2;
+ (id)view:(id)arg1 toFixedWidth:(double)arg2;
+ (id)view:(id)arg1 toFixedHeight:(double)arg2;
+ (id)constrainExtentOfView:(id)arg1 toSiblingView:(id)arg2 withParent:(id)arg3;
+ (id)rightOfChild:(id)arg1 toLeftOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)leftOfChild:(id)arg1 toRightOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)bottomOfChild:(id)arg1 toTopOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)topOfChild:(id)arg1 toBottomOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)rightOfChild:(id)arg1 toRightOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)leftOfChild:(id)arg1 toLeftOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)bottomOfChild:(id)arg1 toBottomOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)topOfChild:(id)arg1 toTopOfSibling:(id)arg2 withFixedMargin:(double)arg3 inParent:(id)arg4;
+ (id)sizeOfChild:(id)arg1 toSizeOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)heightOfChild:(id)arg1 toHeightOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)widthOfChild:(id)arg1 toWidthOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)centerOfChild:(id)arg1 toCenterOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)centerYOfChild:(id)arg1 toCenterYOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)centerXOfChild:(id)arg1 toCenterXOfSibling:(id)arg2 inParent:(id)arg3;
+ (id)extentOfChild:(id)arg1 toExtentOfParent:(id)arg2;
+ (id)sidesOfChild:(id)arg1 toSidesOfParent:(id)arg2 margin:(double)arg3;
+ (id)sidesOfChild:(id)arg1 toSidesOfParent:(id)arg2;
+ (id)rightOfChild:(id)arg1 toRightOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)leftOfChild:(id)arg1 toLeftOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)bottomOfChild:(id)arg1 toBottomOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)bottomOfChild:(id)arg1 toBottomOfParent:(id)arg2;
+ (id)topOfChild:(id)arg1 toTopOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)topOfChild:(id)arg1 toTopOfParent:(id)arg2;
+ (id)centerOfChild:(id)arg1 toCenterOfParent:(id)arg2;
+ (id)centerYOfChild:(id)arg1 toCenterYOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)centerYOfChild:(id)arg1 toCenterYOfParent:(id)arg2;
+ (id)centerXOfChild:(id)arg1 toCenterXOfParent:(id)arg2 withFixedMargin:(double)arg3;
+ (id)centerXOfChild:(id)arg1 toCenterXOfParent:(id)arg2;
+ (id)view:(id)arg1 attr:(long long)arg2 toFixedValue:(double)arg3;
+ (id)attrOfChild:(id)arg1 toSameAttrOfSibling:(id)arg2 inParent:(id)arg3 attr:(long long)arg4 constant:(double)arg5;
+ (id)attrOfChild:(id)arg1 toSameAttrOfParent:(id)arg2 attr:(long long)arg3 constant:(double)arg4;
@end

