//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutConstraint.h"

@interface NSLayoutConstraint (Extensions)
+ (id)constraintsToSetWidth:(double)arg1 andHeight:(double)arg2 forView:(id)arg3;
+ (id)constraintToSetHeight:(double)arg1 forView:(id)arg2;
+ (id)constraintToSetWidth:(double)arg1 forView:(id)arg2;
+ (id)constraintsToFillView:(id)arg1 withView:(id)arg2 edgeInsets:(struct UIEdgeInsets)arg3;
+ (id)constraintsToFillView:(id)arg1 withView:(id)arg2;
+ (id)constraintsToFillVerticallyView:(id)arg1 withView:(id)arg2 edgeInsets:(struct UIEdgeInsets)arg3;
+ (id)constraintsToFillVerticallyView:(id)arg1 withView:(id)arg2;
+ (id)constraintsToFillHorizontallyView:(id)arg1 withView:(id)arg2 edgeInsets:(struct UIEdgeInsets)arg3;
+ (id)constraintsToFillHorizontallyView:(id)arg1 withView:(id)arg2;
+ (id)constraintsToCenterHorizontallyView:(id)arg1 withReferenceView:(id)arg2;
+ (id)constraintsToCenterVerticallyView:(id)arg1 withReferenceView:(id)arg2;
+ (id)constraintsToCenterView:(id)arg1 withReferenceView:(id)arg2;
- (id)description;
@end

