//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (SafeAccess)
- (void)shuffle;
- (void)reverse;
- (void)appendFloat:(float)arg1;
- (void)appendChar:(BOOL)arg1;
- (void)appendUnsignedInteger:(unsigned long long)arg1;
- (void)appendInteger:(long long)arg1;
- (void)appendInt:(int)arg1;
- (void)appendBool:(_Bool)arg1;
- (void)appendString:(id)arg1;
- (void)insertObjects:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)prependObjects:(id)arg1;
- (void)appendObjects:(id)arg1;
- (void)prependObject:(id)arg1;
- (void)appendObject:(id)arg1;
- (id)popLastObject;
- (id)popFirstObject;
- (void)removeFirstObject;
@end

