//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

@interface NSNumber (Round)
- (id)floorWithDigit:(unsigned long long)arg1;
- (id)ceilWithDigit:(unsigned long long)arg1;
- (id)roundWithDigit:(unsigned long long)arg1;
@end

