//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (QuickCopy)
+ (_Bool)isNSObjectClass:(Class)arg1;
- (_Bool)quickDeepCopy:(id)arg1;
- (_Bool)quickCopy:(id)arg1;
@end

