//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (Runtime)
+ (SEL)tempSel:(long long)arg1;
+ (_Bool)swizzleInstanceMethod:(SEL)arg1 withBlock:(id)arg2;
+ (_Bool)swizzleClassMethod:(SEL)arg1 withBlock:(id)arg2;
+ (_Bool)swizzleInstanceMethod:(SEL)arg1 with:(SEL)arg2;
+ (_Bool)swizzleClassMethod:(SEL)arg1 with:(SEL)arg2;
@end

