//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (KVO)
- (void)removeBlockObserverForKeyPath:(id)arg1;
- (void)addObserverForKeyPath:(id)arg1 options:(unsigned long long)arg2 context:(void *)arg3 withBlock:(CDUnknownBlockType)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeBlockObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4 withBlock:(CDUnknownBlockType)arg5;
@end

