//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (QuickAssociated)
- (void)quickRemoveAssociatedValues;
- (id)quickGetAssociatedValueForKey:(void *)arg1;
- (void)quickCopyAssociateValue:(id)arg1 withKey:(void *)arg2;
- (void)quickWeaklyAssociateValue:(id)arg1 withKey:(void *)arg2;
- (void)quickAssociateValue:(id)arg1 withKey:(void *)arg2;
- (void)quickAssociateValue:(id)arg1 withKey:(void *)arg2 withType:(unsigned long long)arg3;
@end

