//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (UIDebuggingInformationOverlayEnable)
+ (void)prepareDebuggingOverlaySwizzled;
+ (void)swizzleSelector:(SEL)arg1 newSelector:(SEL)arg2 forClass:(Class)arg3 isClassMethod:(_Bool)arg4;
+ (void)load;
@end

