//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (Reflect)
+ (id)decodeType:(const char *)arg1;
+ (id)dictionaryWithProperty:(struct objc_property *)arg1;
+ (id)instanceVariable;
+ (id)protocolList;
+ (id)registedClassList;
+ (id)methodList;
+ (id)propertiesWithCodeFormat;
+ (id)propertiesInfo;
+ (id)propertyKeys;
+ (_Bool)isSystemClass;
+ (id)superClassName;
+ (id)className;
- (_Bool)hasIvarForKey:(id)arg1;
- (_Bool)hasPropertyForKey:(id)arg1;
- (id)protocolList;
- (id)methodListInfo;
- (id)methodList;
- (id)propertiesInfo;
- (id)propertyKeys;
- (id)propertyDictionary;
- (_Bool)isSystemClass;
- (id)superClassName;
- (id)className;
@end

