//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (HTML)
- (id)stringByConvertingHTMLToPlainText;
- (id)stringByStrippingTags;
- (id)stringByLinkifyingURLs;
- (id)stringByRemovingNewLinesAndWhitespace;
- (id)stringWithNewLinesAsBRs;
- (id)stringByUnescapingFromHTML;
- (id)stringByEscapingForAsciiHTML;
- (id)stringByEscapingForHTML;
- (id)stringByEscapingHTMLUsingTable:(CDStruct_6a59ab51 *)arg1 ofSize:(unsigned long long)arg2 escapingUnicode:(_Bool)arg3;
@end

