//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Regex)
+ (_Bool)accurateVerifyIDCardNumber:(id)arg1;
- (id)matchedResultWithRegex:(id)arg1;
- (id)firstMatchedResultWithRegex:(id)arg1;
- (id)firstMatchedGroupWithRegex:(id)arg1;
- (id)matchWithRegex:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)matchWithRegex:(id)arg1;
- (_Bool)isIPAddress;
- (_Bool)bankCardluhmCheck;
- (_Bool)isValidTaxNo;
- (_Bool)isValidPostalcode;
- (_Bool)isValidChinese;
- (_Bool)isValidUrl;
- (_Bool)isMacAddress;
- (_Bool)isCarNumber;
- (_Bool)simpleVerifyIdentityCardNum;
- (_Bool)isEmailAddress;
- (_Bool)isMobileNumber;
- (_Bool)isMobileNumberClassification;
- (_Bool)isValidateByRegex:(id)arg1;
@end

