//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Emoji)
+ (void)initializeEmojiCheatCodes;
- (id)removeHTML2:(id)arg1;
- (id)removedEmojiString;
- (_Bool)isIncludingEmoji;
- (_Bool)isFuckEmoji;
- (_Bool)isEmoji;
- (id)stringByReplacingEmojiUnicodeWithCheatCodes;
- (id)stringByReplacingEmojiCheatCodesWithUnicode;
@end

