//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (QRcode)
- (id)imageBlackToTransparent:(id)arg1 withRed:(double)arg2 andGreen:(double)arg3 andBlue:(double)arg4;
- (id)createQRForString:(id)arg1;
- (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
- (id)QRcode;
@end

