//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (AES)
- (id)AES128operation:(unsigned int)arg1 data:(id)arg2 key:(id)arg3 iv:(id)arg4;
- (id)decryptWithAESwithKey:(id)arg1 ivParameter:(id)arg2;
- (id)encryptWithAESwithKey:(id)arg1 ivParameter:(id)arg2;
@end

