//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Contains)
- (int)wordsCount;
- (_Bool)containsString:(id)arg1;
- (_Bool)containsCharacterSet:(id)arg1;
- (_Bool)isContainBlank;
- (_Bool)isContainChinese;
@end

