//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Size)
+ (struct CGSize)sizeWithText:(id)arg1 andFont:(id)arg2 andMaxSize:(struct CGSize)arg3;
- (struct CGSize)sizeWithFont:(id)arg1 constrainedToHeight:(double)arg2;
- (struct CGSize)sizeWithFont:(id)arg1 constrainedToWidth:(double)arg2;
- (double)widthWithFont:(id)arg1 constrainedToHeight:(double)arg2;
- (double)heightWithFont:(id)arg1 constrainedToWidth:(double)arg2;
- (struct CGSize)sizeWithFont:(id)arg1 andMaxSize:(struct CGSize)arg2;
@end

