//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (VersionCompare)
- (_Bool)needsToUpdateToVersion:(id)arg1 mainVersionIntegerCount:(long long)arg2;
- (id)getMainVersionWithIntegerCount:(long long)arg1;
- (_Bool)isEqualOrNewerThanVersion:(id)arg1;
- (_Bool)isEqualOrOlderThanVersion:(id)arg1;
- (_Bool)isEqualToVersion:(id)arg1;
- (_Bool)isNewerThanVersion:(id)arg1;
- (_Bool)isOlderThanVersion:(id)arg1;
- (long long)compareToVersion:(id)arg1;
@end

