//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Path)
+ (id)filePathForSystemFile:(unsigned long long)arg1 withFileName:(id)arg2;
+ (id)pathForSystemFile:(unsigned long long)arg1;
+ (id)filePathAtPreferencesWithFileName:(id)arg1;
+ (id)pathForPreferences;
+ (id)filePathAtTempWithFileName:(id)arg1;
+ (id)pathForTemp;
+ (id)filePathAtMainBundleWithFileName:(id)arg1;
+ (id)pathForMainBundle;
+ (id)filePathAtCachesWithFileName:(id)arg1;
+ (id)pathForCaches;
+ (id)filePathAtDocumentsWithFileName:(id)arg1;
+ (id)pathForDocuments;
@end

