//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Color)
+ (void)registerColors:(id)arg1;
+ (id)registeredColorForKey:(id)arg1;
+ (void)clearRegisteredColorForKey:(id)arg1;
+ (void)registerColor:(id)arg1 withKey:(id)arg2;
+ (id)webColorForKey:(id)arg1;
+ (void)load;
- (id)representedColor;
- (id)colorFromName;
- (id)colorFromRGBAcode;
- (id)colorFromRGBcode;
@end

