//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLRequest.h"

@interface NSURLRequest (Params)
+ (id)queryStringComponentsFromKey:(id)arg1 arrayValue:(id)arg2;
+ (id)queryStringComponentsFromKey:(id)arg1 dictionaryValue:(id)arg2;
+ (id)queryStringComponentsFromKey:(id)arg1 value:(id)arg2;
+ (id)URLfromParameters:(id)arg1;
+ (id)requestGETWithURL:(id)arg1 parameters:(id)arg2;
- (id)initWithURL:(id)arg1 parameters:(id)arg2;
@end

