//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLRequest.h"

@interface NSURLRequest (Upload)
+ (id)requestWithURL:(id)arg1 fileURLs:(id)arg2 fileNames:(id)arg3 name:(id)arg4;
+ (id)requestWithURL:(id)arg1 fileURLs:(id)arg2 name:(id)arg3;
+ (id)requestWithURL:(id)arg1 fileURL:(id)arg2 fileName:(id)arg3 name:(id)arg4;
+ (id)requestWithURL:(id)arg1 fileURL:(id)arg2 name:(id)arg3;
@end

