//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLSession.h"

@interface NSURLSession (SynchronousTask)
- (id)sendSynchronousUploadTaskWithRequest:(id)arg1 fromData:(id)arg2 returningResponse:(id *)arg3 error:(id *)arg4;
- (id)sendSynchronousUploadTaskWithRequest:(id)arg1 fromFile:(id)arg2 returningResponse:(id *)arg3 error:(id *)arg4;
- (id)sendSynchronousDownloadTaskWithRequest:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3;
- (id)sendSynchronousDownloadTaskWithURL:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3;
- (id)sendSynchronousDataTaskWithRequest:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3;
- (id)sendSynchronousDataTaskWithURL:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3;
@end

