//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (UQ_URLQuery)
- (id)URLByReplacingQueryWithDictionary:(id)arg1 withSortedKeys:(_Bool)arg2;
- (id)URLByReplacingQueryWithDictionary:(id)arg1;
- (id)URLByRemovingQuery;
- (id)URLByAppendingQueryDictionary:(id)arg1 withSortedKeys:(_Bool)arg2;
- (id)URLByAppendingQueryDictionary:(id)arg1;
- (id)queryDictionary;
@end

