//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSUserDefaults.h"

@interface NSUserDefaults (iCloudSync)
- (_Bool)synchronizeAlsoiCloudSync:(_Bool)arg1;
- (void)removeObjectForKey:(id)arg1 iCloudSync:(_Bool)arg2;
- (id)objectForKey:(id)arg1 iCloudSync:(_Bool)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 iCloudSync:(_Bool)arg3;
- (void)removeValueForKey:(id)arg1 iCloudSync:(_Bool)arg2;
- (id)valueForKey:(id)arg1 iCloudSync:(_Bool)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2 iCloudSync:(_Bool)arg3;
@end

