//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableAttributedString;

@interface SIAttributedStringBuilder : NSObject
{
    NSMutableAttributedString *attrString;
    long long paragraphIndex;
}

+ (id)builderWith:(id)arg1;
- (void).cxx_destruct;
- (id)commit;
- (void)insert:(long long)arg1 attrBuilder:(id)arg2;
- (void)insert:(long long)arg1 attrstring:(id)arg2;
- (id)nextParagraph;
- (id)firstParagraph;
- (id)regularExpression:(id)arg1 all:(_Bool)arg2;
- (id)includeString:(id)arg1 all:(_Bool)arg2;
- (id)searchString:(id)arg1 options:(unsigned long long)arg2 all:(_Bool)arg3;
- (id)characterSet:(id)arg1;
- (id)firstNRange:(long long)arg1;
- (id)firstRange;
- (id)lastNRange:(long long)arg1;
- (id)lastRange;
- (id)allRange;
- (id)range:(struct _NSRange)arg1;
- (id)initWithString:(id)arg1;

@end

