//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableAttributedString;

@interface SIAttributedStringRange : NSObject
{
    NSMutableArray *_ranges;
    NSMutableAttributedString *_attrString;
}

- (void).cxx_destruct;
- (id)setAttributes:(id)arg1;
- (id)setStrokeWidth:(double)arg1;
- (id)setStrokeColor:(id)arg1;
- (id)setExpansion:(double)arg1;
- (id)setObliqueness:(double)arg1;
- (id)setUnderlineColor:(id)arg1;
- (id)setBaselineOffset:(double)arg1;
- (id)setLink:(id)arg1;
- (id)setAttachment:(id)arg1;
- (id)setTextEffect:(id)arg1;
- (id)setShadow:(id)arg1;
- (id)setUnderlineStyle:(long long)arg1;
- (id)setStrikethroughColor:(id)arg1;
- (id)setStrikethroughStyle:(int)arg1;
- (id)setLineSpacing:(double)arg1;
- (id)setKern:(double)arg1;
- (id)setLigature:(_Bool)arg1;
- (id)setParagraphStyle:(id)arg1;
- (id)setBackgroundColor:(id)arg1;
- (id)setTextColor:(id)arg1;
- (id)setFont:(id)arg1;
- (void)enumRange:(CDUnknownBlockType)arg1;
- (void)addRange:(struct _NSRange)arg1;
- (id)initWithAttributeString:(id)arg1;

@end

