//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SIAuthorizationManager : NSObject
{
}

+ (id)sharedManager;
- (id)writeObjectTypes;
- (id)readObjectTypes;
- (void)requestAuthorizationTypeHealthCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeReminderCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeContactCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeEventCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeSpeechCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypePushNotificationCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeBluetoothCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeLocationCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeMicrophoneCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeMediaCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypeCameraCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationTypePhotoCompletion:(CDUnknownBlockType)arg1;
- (void)requestAuthorizationType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;

@end

