//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"
#import "CBPeripheralDelegate.h"

@class CBCentralManager, CBCharacteristic, CBPeripheral, CBService, NSMutableArray, NSString, NSTimer;

@interface SIBluetoothManager : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
{
    id <SIBluetoothManagerDelegate> _delegate;
    unsigned long long _bleStatue;
    NSString *_serviceUUID;
    NSString *_outputCharacteristicUUID;
    NSString *_inputCharacteristicUUID;
    CBCentralManager *_centralManager;
    CBPeripheral *_peripheral;
    CBService *_service;
    CBCharacteristic *_inputCharacteristic;
    CBCharacteristic *_outPutcharacteristic;
    NSTimer *_scanCutdownTimer;
    NSMutableArray *_mPeripherals;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *mPeripherals; // @synthesize mPeripherals=_mPeripherals;
@property(retain, nonatomic) NSTimer *scanCutdownTimer; // @synthesize scanCutdownTimer=_scanCutdownTimer;
@property(retain, nonatomic) CBCharacteristic *outPutcharacteristic; // @synthesize outPutcharacteristic=_outPutcharacteristic;
@property(retain, nonatomic) CBCharacteristic *inputCharacteristic; // @synthesize inputCharacteristic=_inputCharacteristic;
@property(retain, nonatomic) CBService *service; // @synthesize service=_service;
@property(retain, nonatomic) CBPeripheral *peripheral; // @synthesize peripheral=_peripheral;
@property(retain, nonatomic) CBCentralManager *centralManager; // @synthesize centralManager=_centralManager;
@property(retain, nonatomic) NSString *inputCharacteristicUUID; // @synthesize inputCharacteristicUUID=_inputCharacteristicUUID;
@property(retain, nonatomic) NSString *outputCharacteristicUUID; // @synthesize outputCharacteristicUUID=_outputCharacteristicUUID;
@property(retain, nonatomic) NSString *serviceUUID; // @synthesize serviceUUID=_serviceUUID;
@property(nonatomic) unsigned long long bleStatue; // @synthesize bleStatue=_bleStatue;
@property(nonatomic) __weak id <SIBluetoothManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateBLEStatue:(unsigned long long)arg1;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)sendMsg:(id)arg1;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)disconnectDevice;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)reConnectDevice;
- (void)connectDeviceWithCBPeripheral:(id)arg1 andServiceUUID:(id)arg2 andOutputCharacteristicUUID:(id)arg3 andInputCharacteristicUUID:(id)arg4;
- (void)stopScanDevice;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)scanDevice;
- (void)centralManagerDidUpdateState:(id)arg1;
- (unsigned long long)getBLEStatue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

