//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GHConsoleWindow, NSDate, NSDateFormatter, NSMutableString, NSString, UIPanGestureRecognizer;

@interface SIConsoleManager : NSObject
{
    NSDate *_timestamp;
    NSString *_timeString;
    _Bool _isShowConsole;
    _Bool _isFullScreen;
    NSString *_string;
    NSMutableString *_logSting;
    long long _currentLogCount;
    UIPanGestureRecognizer *_panOutGesture;
    GHConsoleWindow *_consoleWindow;
    NSString *_funcString;
    NSDateFormatter *_formatter;
    NSString *_msgString;
    NSDate *_now;
}

+ (id)sharedConsole;
@property(retain, nonatomic) NSDate *now; // @synthesize now=_now;
@property(copy, nonatomic) NSString *msgString; // @synthesize msgString=_msgString;
@property(retain, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;
@property(copy, nonatomic) NSString *funcString; // @synthesize funcString=_funcString;
@property(retain, nonatomic) GHConsoleWindow *consoleWindow; // @synthesize consoleWindow=_consoleWindow;
@property(retain, nonatomic) UIPanGestureRecognizer *panOutGesture; // @synthesize panOutGesture=_panOutGesture;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) long long currentLogCount; // @synthesize currentLogCount=_currentLogCount;
@property(copy, nonatomic) NSMutableString *logSting; // @synthesize logSting=_logSting;
@property(nonatomic) _Bool isShowConsole; // @synthesize isShowConsole=_isShowConsole;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
- (void)doubleTapTextView:(id)arg1;
- (void)panOutTextView:(id)arg1;
- (void)swipeLogView:(id)arg1;
- (void)clearAllText;
- (void)printMSG:(id)arg1 andFunc:(const char *)arg2 andLine:(long long)arg3;
- (void)function:(const char *)arg1 line:(unsigned long long)arg2 format:(id)arg3;
- (void)stopPringting;
- (void)startPrintLog;

@end

