//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSOutputStream, NSString, NSURLSessionDataTask;

@interface SIDownloadInfo : NSObject
{
    long long _state;
    long long _totalBytesWritten;
    long long _bytesWritten;
    NSString *_url;
    NSError *_error;
    long long _totalBytesExpectedToWrite;
    NSString *_filename;
    NSString *_file;
    CDUnknownBlockType _progressChangeBlock;
    CDUnknownBlockType _stateChangeBlock;
    NSURLSessionDataTask *_task;
    NSOutputStream *_stream;
}

@property(retain, nonatomic) NSOutputStream *stream; // @synthesize stream=_stream;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(copy, nonatomic) CDUnknownBlockType stateChangeBlock; // @synthesize stateChangeBlock=_stateChangeBlock;
@property(copy, nonatomic) CDUnknownBlockType progressChangeBlock; // @synthesize progressChangeBlock=_progressChangeBlock;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(nonatomic) long long totalBytesExpectedToWrite; // @synthesize totalBytesExpectedToWrite=_totalBytesExpectedToWrite;
@property(nonatomic) long long totalBytesWritten; // @synthesize totalBytesWritten=_totalBytesWritten;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long bytesWritten; // @synthesize bytesWritten=_bytesWritten;
- (void).cxx_destruct;
- (void)didCompleteWithError:(id)arg1;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1;
- (void)suspend;
- (void)willResume;
- (void)resume;
- (void)cancel;
@property(nonatomic) long long state;
- (void)notifyStateChange;
- (void)notifyProgressChange;
- (void)setupTask:(id)arg1;

@end

