//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class CADisplayLink, CATextLayer;

@interface SIFPSManager : UIWindow
{
    CADisplayLink *_displayLink;
    CATextLayer *_fpsTextLayer;
    double _lastTime;
    unsigned long long _count;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)dealloc;
- (void)becomeKeyWindow;
- (void)applicationWillResignActiveNotification;
- (void)applicationDidBecomeActiveNotification;
- (void)close;
- (void)open;
- (void)displayLinkTick:(id)arg1;
- (id)init;

@end

