//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SIMediatorManager : NSObject
{
    NSMutableDictionary *_cachedTarget;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *cachedTarget; // @synthesize cachedTarget=_cachedTarget;
- (void).cxx_destruct;
- (void)releaseCachedTargetWithTargetName:(id)arg1;
- (id)performTarget:(id)arg1 action:(id)arg2 params:(id)arg3 shouldCacheTarget:(_Bool)arg4;
- (id)performActionWithUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

