//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSPointerArray;

@interface SIProxyManager : NSObject
{
    struct _opaque_pthread_mutex_t lock;
    NSPointerArray *_targets;
}

@property(retain, nonatomic) NSPointerArray *targets; // @synthesize targets=_targets;
- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)removeTarget:(id)arg1;
- (void)addTarger:(id)arg1;
- (void)dealloc;
- (id)init;

@end

