//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SIPushNotificationManager : NSObject
{
}

+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void)registerPushNotificationWithIdentifier:(id)arg1 content:(id)arg2 trigger:(id)arg3;
- (void)locationPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 longitude:(double)arg5 latitude:(double)arg6 radius:(long long)arg7 notifyOnEntry:(_Bool)arg8 ontifyOnExit:(_Bool)arg9 soundName:(id)arg10 userInfo:(id)arg11 repeat:(_Bool)arg12;
- (void)locationPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 longitude:(double)arg5 latitude:(double)arg6 radius:(long long)arg7 notifyOnEntry:(_Bool)arg8 notifyOnExit:(_Bool)arg9 userInfo:(id)arg10 repeat:(_Bool)arg11;
- (void)interactivePushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 identifierArray:(id)arg5 actionArray:(id)arg6 soundName:(id)arg7 timeInterval:(long long)arg8 userInfo:(id)arg9 repeat:(_Bool)arg10;
- (void)interactivePushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 identifierArray:(id)arg5 actionArray:(id)arg6 timeInterval:(long long)arg7 userInfo:(id)arg8 repeat:(_Bool)arg9;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fireDate:(id)arg5 soundName:(id)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fireDate:(id)arg5 userInfo:(id)arg6 repeat:(_Bool)arg7;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 year:(id)arg5 month:(id)arg6 day:(id)arg7 hour:(id)arg8 minute:(id)arg9 second:(id)arg10 soundName:(id)arg11 userInfo:(id)arg12 repeat:(_Bool)arg13;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 year:(id)arg5 month:(id)arg6 day:(id)arg7 hour:(id)arg8 minute:(id)arg9 second:(id)arg10 userInfo:(id)arg11 repeat:(_Bool)arg12;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 weekday:(id)arg5 hour:(id)arg6 minute:(id)arg7 second:(id)arg8 soundName:(id)arg9 userInfo:(id)arg10 repeat:(_Bool)arg11;
- (void)timingPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 weekday:(id)arg5 hour:(id)arg6 minute:(id)arg7 second:(id)arg8 userInfo:(id)arg9 repeat:(_Bool)arg10;
- (void)videoPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 urlString:(id)arg5 soundName:(id)arg6 timeInterval:(long long)arg7 userInfo:(id)arg8 repeat:(_Bool)arg9;
- (void)videoPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 urlString:(id)arg5 timeInterval:(long long)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)videoPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fileName:(id)arg5 soundName:(id)arg6 timeInterval:(long long)arg7 userInfo:(id)arg8 repeat:(_Bool)arg9;
- (void)videoPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fileName:(id)arg5 timeInterval:(long long)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)graphicsPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 urlString:(id)arg5 soundName:(id)arg6 timeInterval:(long long)arg7 userInfo:(id)arg8 repeat:(_Bool)arg9;
- (void)graphicsPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 urlString:(id)arg5 timeInterval:(long long)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)graphicsPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fileName:(id)arg5 soundName:(id)arg6 timeInterval:(long long)arg7 userInfo:(id)arg8 repeat:(_Bool)arg9;
- (void)graphicsPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 fileName:(id)arg5 timeInterval:(long long)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)normalPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 soundName:(id)arg5 timeInterval:(long long)arg6 userInfo:(id)arg7 repeat:(_Bool)arg8;
- (void)normalPushNotificationWithTitle:(id)arg1 subTitle:(id)arg2 body:(id)arg3 identifier:(id)arg4 timeInterval:(long long)arg5 userInfo:(id)arg6 repeat:(_Bool)arg7;
- (void)requestAuthorizationPushNotificationWithCompletion:(CDUnknownBlockType)arg1;

@end

