//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LAContext, NSError, NSString;

@interface SITouchIDManager : NSObject
{
    NSString *_alertDescription;
    CDUnknownBlockType _touchIDAllowBlock;
    CDUnknownBlockType _passSuccessBlock;
    CDUnknownBlockType _passFailBlock;
    LAContext *_authenticationContext;
    NSError *_lastError;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
@property(retain, nonatomic) LAContext *authenticationContext; // @synthesize authenticationContext=_authenticationContext;
@property(copy, nonatomic) CDUnknownBlockType passFailBlock; // @synthesize passFailBlock=_passFailBlock;
@property(copy, nonatomic) CDUnknownBlockType passSuccessBlock; // @synthesize passSuccessBlock=_passSuccessBlock;
@property(copy, nonatomic) CDUnknownBlockType touchIDAllowBlock; // @synthesize touchIDAllowBlock=_touchIDAllowBlock;
@property(retain, nonatomic) NSString *alertDescription; // @synthesize alertDescription=_alertDescription;
- (void).cxx_destruct;
- (_Bool)errorDidSend:(id)arg1;
- (void)sendFailWithError:(id)arg1;
@property(readonly, nonatomic) _Bool isTouchIDAllowed;
@property(readonly, nonatomic) _Bool isTouchIDAvailable;
- (void)tryToPass;
- (id)init;

@end

