//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, UIColor;

@interface Skeleton : UIView
{
    UIColor *_skeletonColor;
    long long _animationStyle;
    CAGradientLayer *_somoLayer;
}

@property(retain, nonatomic) CAGradientLayer *somoLayer; // @synthesize somoLayer=_somoLayer;
@property(nonatomic) long long animationStyle; // @synthesize animationStyle=_animationStyle;
@property(retain, nonatomic) UIColor *skeletonColor; // @synthesize skeletonColor=_skeletonColor;
- (void).cxx_destruct;
- (void)_animate;
- (void)_setup;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 somoColor:(id)arg2 animationStyle:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1 somoColor:(id)arg2;

@end

