//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, NSTimer, UIImageView, UILabel;

@interface TopWarningView : UIView
{
    float _dimissDelay;
    int _mode;
    NSString *_warningText;
    UIImageView *_iconIgv;
    CDUnknownBlockType _tapHandler;
    UILabel *_label;
    NSTimer *_dimissTimer;
}

@property(retain, nonatomic) NSTimer *dimissTimer; // @synthesize dimissTimer=_dimissTimer;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) float dimissDelay; // @synthesize dimissDelay=_dimissDelay;
@property(copy, nonatomic) CDUnknownBlockType tapHandler; // @synthesize tapHandler=_tapHandler;
@property(retain, nonatomic) UIImageView *iconIgv; // @synthesize iconIgv=_iconIgv;
@property(retain, nonatomic) NSString *warningText; // @synthesize warningText=_warningText;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;
- (void)dismiss;
- (void)tapNow;
- (void)layoutSubviews;
- (void)resetViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

