//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@class NSString;

@interface UIApplication (AppInfo)
+ (id)sharedExtensionApplication;
+ (_Bool)isAppExtension;
- (unsigned long long)sizeOfFolder:(id)arg1;
- (id)cachePath;
- (id)libraryPath;
- (id)documentPath;
- (id)applicationSizeAsString;
- (int)libraryFolderSizeInBytes;
- (id)libraryFolderSizeAsString;
- (int)applicationSizeSizeInBytes;
- (id)cacheFolderSizeAsString;
- (int)cacheFolderSizeInBytes;
- (id)documentsFolderSizeAsString;
- (int)documentsFolderSizeInBytes;
@property(readonly, nonatomic) NSString *appBundleID;
@property(readonly, nonatomic) NSString *appBuild;
@property(readonly, nonatomic) NSString *appVersion;
@property(readonly, nonatomic) NSString *appName;
@end

