//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (Permissions)
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)setSI_locationFailureCallbackProperty:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)locationFailureCallbackProperty;
- (void)setSI_locationSuccessCallbackProperty:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)locationSuccessCallbackProperty;
- (void)setSI_permissionsLocationManager:(id)arg1;
- (id)SI_permissionsLocationManager;
- (void)requestAccessToLocationWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (void)requestAccessToRemindersWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (void)requestAccessToPhotosWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (void)requestAccessToMotionWithSuccess:(CDUnknownBlockType)arg1;
- (void)requestAccessToMicrophoneWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (void)requestAccessToContactsWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (void)requestAccessToCalendarWithSuccess:(CDUnknownBlockType)arg1 andFailure:(CDUnknownBlockType)arg2;
- (int)hasAccessToReminders;
- (int)hasAccessToPhotos;
- (int)hasAccessToLocation;
- (int)hasAccessToContacts;
- (int)hasAccessToCalendar;
- (int)hasAccessToBluetoothLE;
@end

