//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (Authority)
@property(readonly, nonatomic) _Bool isAccessToMicrophone;
@property(readonly, nonatomic) _Bool isAccessToPhotosLibrary;
@property(readonly, nonatomic) _Bool isAccessToReminders;
@property(readonly, nonatomic) _Bool isAccessToCalendar;
@property(readonly, nonatomic) _Bool isAccessToAddressBook;
@property(readonly, nonatomic) _Bool isAccessToLocationData;
@end

