//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@interface UIBarButtonItem (Create)
+ (id)fixedSpaceWithWidth:(double)arg1;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 title:(id)arg3 font:(id)arg4 titleColor:(id)arg5 highlightedColor:(id)arg6 titleEdgeInsets:(struct UIEdgeInsets)arg7;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 title:(id)arg3 titleEdgeInsets:(struct UIEdgeInsets)arg4;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 title:(id)arg3;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 nomalImage:(id)arg3 higeLightedImage:(id)arg4 imageEdgeInsets:(struct UIEdgeInsets)arg5;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 image:(id)arg3 imageEdgeInsets:(struct UIEdgeInsets)arg4;
+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2 image:(id)arg3;
@end

