//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBezierPath.h"

@interface UIBezierPath (BasicShapes)
+ (id)stars:(unsigned long long)arg1 shapeInFrame:(struct CGRect)arg2;
+ (id)starShape:(struct CGRect)arg1;
+ (id)beakerShape:(struct CGRect)arg1;
+ (id)martiniShape:(struct CGRect)arg1;
+ (id)userShape:(struct CGRect)arg1;
+ (id)heartShape:(struct CGRect)arg1;
+ (struct CGRect)maximumSquareFrameThatFits:(struct CGRect)arg1;
@end

