//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBezierPath.h"

@interface UIBezierPath (Symbol)
+ (id)customBezierPathOfPencilSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2 thick:(double)arg3;
+ (id)customBezierPathOfArrowSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2 thick:(double)arg3 direction:(long long)arg4;
+ (id)customBezierPathOfCrossSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2 thick:(double)arg3;
+ (id)customBezierPathOfCheckSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2 thick:(double)arg3;
+ (id)customBezierPathOfMinusSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2;
+ (id)customBezierPathOfPlusSymbolWithRect:(struct CGRect)arg1 scale:(double)arg2;
@end

