//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBezierPath.h"

@interface UIBezierPath (TextPaths)
+ (id)pathForMultilineAttributedString:(id)arg1 maxWidth:(double)arg2;
+ (id)pathForAttributedString:(id)arg1;
+ (id)pathForMultilineString:(id)arg1 withFont:(id)arg2 maxWidth:(double)arg3 textAlignment:(long long)arg4;
+ (id)pathForString:(id)arg1 withFont:(id)arg2;
@end

