//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (CountDown)
- (void)startTime:(long long)arg1 waitBlock:(CDUnknownBlockType)arg2 finishBlock:(CDUnknownBlockType)arg3;
@end

