//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (Make)
+ (id)__searchForCrayolaByName:(id)arg1;
+ (id)__searchForColorByName:(id)arg1;
+ (void)red:(double)arg1 green:(double)arg2 blue:(double)arg3 toHue:(double *)arg4 saturation:(double *)arg5 brightness:(double *)arg6;
+ (void)hue:(double)arg1 saturation:(double)arg2 brightness:(double)arg3 toRed:(double *)arg4 green:(double *)arg5 blue:(double *)arg6;
+ (id)colorWithRGBDictionary:(id)arg1;
+ (id)colorWithNormalizedRGBDictionary:(id)arg1;
+ (id)colorWithByteRGBDictionary:(id)arg1;
+ (id)colorWithHue:(double)arg1 saturation:(double)arg2 lightness:(double)arg3 alpha:(double)arg4;
+ (id)gradientFromColor:(id)arg1 toColor:(id)arg2 withHeight:(double)arg3;
+ (id)colorWithCSSDescription:(id)arg1;
+ (id)crayonWithName:(id)arg1;
+ (id)colorWithName:(id)arg1;
+ (id)colorAndAlphaWithHexString:(id)arg1;
+ (id)colorWithHexString:(id)arg1;
+ (id)colorWithGrayHex:(unsigned char)arg1;
+ (id)colorWithGray:(double)arg1;
+ (id)colorWithRGBAHex:(unsigned int)arg1;
+ (id)colorWithRGBHex:(unsigned int)arg1;
+ (id)randomHSBColorWithMinSaturation:(double)arg1 minBrightness:(double)arg2;
+ (id)randomHSBColor;
+ (id)randomColor;
+ (id)colorWithString:(id)arg1;
+ (void)load;
- (id)hexStringFromColorAndAlpha;
- (id)closestCrayonName;
- (id)closestColorName;
- (id)closestColorNameFor:(const char *)arg1;
- (id)cssStringFromColor;
- (id)hexStringFromColor;
- (id)stringFromColor;
- (id)analogousColorsWithStepAngle:(double)arg1 pairCount:(int)arg2;
- (id)triadicColors;
- (id)complementaryColor;
- (id)contrastingColor;
- (id)colorByInterpolatingToColor:(id)arg1 byFraction:(double)arg2;
- (id)colorByDarkeningToColor:(id)arg1;
- (id)colorByLighteningToColor:(id)arg1;
- (id)colorByAddingColor:(id)arg1;
- (id)colorByMultiplyingByColor:(id)arg1;
- (id)colorByDarkeningTo:(double)arg1;
- (id)colorByLighteningTo:(double)arg1;
- (id)colorByAdding:(double)arg1;
- (id)colorByMultiplyingBy:(double)arg1;
- (id)colorByDarkeningToRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)colorByLighteningToRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)colorByAddingRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)colorByMultiplyingByRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)colorByLuminanceMapping;
@property(readonly, nonatomic) unsigned int rgbaHex;
@property(readonly, nonatomic) unsigned int rgbHex;
@property(readonly, nonatomic) double luminance;
@property(readonly, nonatomic) double alpha;
@property(readonly, nonatomic) double brightness;
@property(readonly, nonatomic) double saturation;
@property(readonly, nonatomic) double hue;
@property(readonly, nonatomic) double white;
@property(readonly, nonatomic) double blue;
@property(readonly, nonatomic) double green;
@property(readonly, nonatomic) double red;
- (_Bool)hue:(double *)arg1 saturation:(double *)arg2 brightness:(double *)arg3 alpha:(double *)arg4;
- (_Bool)red:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
- (id)arrayFromRGBAComponents;
@property(readonly, nonatomic) _Bool canProvideRGBComponents;
- (id)colorSpaceString;
@property(readonly, nonatomic) int colorSpaceModel;
@end

