//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@interface UIControl (ALActionBlocks)
- (id)actionBlocksArray;
- (void)removeActionBlocksForControlEvents:(unsigned long long)arg1;
- (void)handleControlEvents:(unsigned long long)arg1 withBlock:(CDUnknownBlockType)arg2;
@end

