//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (FlatColors)
+ (id)flatAsbestosColor;
+ (id)flatConcreteColor;
+ (id)flatSilverColor;
+ (id)flatCloudsColor;
+ (id)flatPomegranateColor;
+ (id)flatAlizarinColor;
+ (id)flatPumpkinColor;
+ (id)flatCarrotColor;
+ (id)flatOrangeColor;
+ (id)flatSunFlowerColor;
+ (id)flatMidnightBlueColor;
+ (id)flatWetAsphaltColor;
+ (id)flatWisteriaColor;
+ (id)flatAmethystColor;
+ (id)flatBelizeHoleColor;
+ (id)flatPeterRiverColor;
+ (id)flatNephritisColor;
+ (id)flatEmeraldColor;
+ (id)flatGreenSeaColor;
+ (id)flatTurquoiseColor;
@end

