//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@class NSString;

@interface UIDevice (NetWork)
- (id)ipAddressWithIfaName:(id)arg1;
@property(readonly, nonatomic) unsigned long long networkType;
@property(readonly, nonatomic) NSString *ipAddressCell;
@property(readonly, nonatomic) NSString *ipAddressWIFI;
@property(readonly, nonatomic) NSString *macAddress;
@end

