//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@class NSDate, NSString;

@interface UIDevice (Device)
@property(readonly, nonatomic) int deviceFamily;
@property(readonly, nonatomic) NSString *hardwareDesc;
@property(readonly, nonatomic) unsigned long long hardware;
@property(readonly, nonatomic) NSString *hardwareString;
@property(readonly, nonatomic) NSDate *systemUptime;
@property(readonly, nonatomic) _Bool canCallPhone;
@property(readonly, nonatomic) _Bool hasCamera;
@property(readonly, nonatomic) _Bool isRetina;
@property(readonly, nonatomic) _Bool isJailbroken;
@property(readonly, nonatomic) _Bool isSimulator;
@property(readonly, nonatomic) _Bool isPad;
@end

