//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (Disk)
@property(readonly, nonatomic) long long memoryPurgable;
@property(readonly, nonatomic) long long memoryWired;
@property(readonly, nonatomic) long long memoryInactive;
@property(readonly, nonatomic) long long memoryActive;
@property(readonly, nonatomic) long long memoryFree;
@property(readonly, nonatomic) long long memoryUsed;
@property(readonly, nonatomic) long long memoryTotal;
@property(readonly, nonatomic) long long diskSpaceUsed;
@property(readonly, nonatomic) long long diskSpaceFree;
@property(readonly, nonatomic) long long diskSpace;
@end

