//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (Make)
+ (id)fontWithCGFont:(struct CGFont *)arg1 size:(double)arg2;
+ (id)fontWithCTFont:(struct __CTFont *)arg1;
- (struct CGFont *)CGFontRef;
- (struct __CTFont *)CTFontRef;
- (id)fontWithNormal;
- (id)fontWithBoldItalic;
- (id)fontWithItalic;
- (id)fontWithBold;
@end

