//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (TTF)
+ (id)fontWithTTFAtPath:(id)arg1 size:(double)arg2;
+ (id)fontWithTTFAtURL:(id)arg1 size:(double)arg2;
@end

