//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (Load)
+ (id)dataFromCGFont:(struct CGFont *)arg1;
+ (id)dataFromFont:(id)arg1;
+ (_Bool)unloadFontFromData:(id)arg1;
+ (id)loadFontFromData:(id)arg1;
+ (void)unloadFontFromPath:(id)arg1;
+ (_Bool)loadFontFromPath:(id)arg1;
@end

