//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizer.h"

@interface UIGestureRecognizer (ALActionBlocks)
+ (id)gestureRecognizerWithBlock:(CDUnknownBlockType)arg1;
- (id)actionBlocksArray;
- (void)setBlock:(CDUnknownBlockType)arg1;
@end

