//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Rotate)
- (id)imageByRotate:(double)arg1 fitSize:(_Bool)arg2;
- (id)imageRotatedByDegrees:(double)arg1;
- (id)imageRotatedByRadians:(double)arg1;
- (id)flipHorizontal;
- (id)flipVertical;
- (id)rotate:(long long)arg1;
- (id)fixOrientation;
@end

