//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Modify)
- (id)imageByRoundCornerRadius:(double)arg1 corners:(unsigned long long)arg2 borderWidth:(double)arg3 borderColor:(id)arg4 borderLineJoin:(int)arg5;
- (id)imageByRoundCornerRadius:(double)arg1 borderWidth:(double)arg2 borderColor:(id)arg3;
- (id)imageByRoundCornerRadius:(double)arg1;
- (id)imageByInsetEdge:(struct UIEdgeInsets)arg1 withColor:(id)arg2;
- (id)imageByCropToRect:(struct CGRect)arg1;
- (id)imageByResizeToSize:(struct CGSize)arg1 contentMode:(long long)arg2;
- (id)imageByResizeToSize:(struct CGSize)arg1;
- (void)drawInRect:(struct CGRect)arg1 withContentMode:(long long)arg2 clipsToBounds:(_Bool)arg3;
@end

