//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Make)
+ (id)imageWithEmoji:(id)arg1 size:(double)arg2;
+ (id)imageWithSize:(struct CGSize)arg1 drawBlock:(CDUnknownBlockType)arg2;
+ (id)imageWithPDF:(id)arg1 size:(struct CGSize)arg2;
+ (id)imageWithPDF:(id)arg1;
+ (id)imageWithPDF:(id)arg1 resize:(_Bool)arg2 size:(struct CGSize)arg3;
@end

