//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Compress)
+ (id)ResizeImageWithImage:(id)arg1 andSize:(struct CGSize)arg2 Scale:(_Bool)arg3;
+ (id)OnlyCompressToDataWithImage:(id)arg1 FileSize:(long long)arg2;
+ (id)OnlyCompressToImageWithImage:(id)arg1 FileSize:(long long)arg2;
+ (void)CompressToImageAtBackgroundWithImage:(id)arg1 ShowSize:(struct CGSize)arg2 FileSize:(long long)arg3 block:(CDUnknownBlockType)arg4;
+ (void)CompressToDataAtBackgroundWithImage:(id)arg1 ShowSize:(struct CGSize)arg2 FileSize:(long long)arg3 block:(CDUnknownBlockType)arg4;
+ (id)CompressToImageWithImage:(id)arg1 ShowSize:(struct CGSize)arg2 FileSize:(long long)arg3;
+ (id)CompressToDataWithImage:(id)arg1 ShowSize:(struct CGSize)arg2 FileSize:(long long)arg3;
@end

