//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Capture)
+ (id)imageWithSize:(struct CGRect)arg1 FromImage:(id)arg2;
+ (id)captureWithView:(id)arg1;
@end

