//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Effect)
- (id)_mergeImageRef:(struct CGImage *)arg1 tintColor:(id)arg2 tintBlendMode:(int)arg3 maskImage:(id)arg4 opaque:(_Bool)arg5;
- (id)imageByBlurRadius:(double)arg1 tintColor:(id)arg2 tintMode:(int)arg3 saturation:(double)arg4 maskImage:(id)arg5;
- (id)imageByBlurWithTint:(id)arg1;
- (id)imageByBlurDark;
- (id)imageByBlurExtraLight;
- (id)imageByBlurLight;
- (id)imageByBlurSoft;
- (id)imageByGrayscale;
- (id)imageByTintColor:(id)arg1;
@end

