//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (CornerRadius)
+ (void)swizzleLayoutSubviews;
+ (void)swizzleDealloc;
+ (void)swizzleMethod:(SEL)arg1 anotherMethod:(SEL)arg2;
- (void)setZyRadius:(double)arg1;
- (double)zyRadius;
- (void)setRoundingCorners:(unsigned long long)arg1;
- (unsigned long long)roundingCorners;
- (void)setZyIsRounding:(_Bool)arg1;
- (_Bool)zyIsRounding;
- (void)setZyHadAddObserver:(_Bool)arg1;
- (_Bool)zyHadAddObserver;
- (void)setZyBorderColor:(id)arg1;
- (id)zyBorderColor;
- (void)setZyBorderWidth:(double)arg1;
- (double)zyBorderWidth;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)zy_LayoutSubviews;
- (void)validateFrame;
- (void)zy_dealloc;
- (void)drawBorder:(id)arg1;
- (void)cornerRadiusRoundingRect;
- (void)cornerRadiusAdvance:(double)arg1 rectCornerType:(unsigned long long)arg2;
- (void)zy_cornerRadiusWithImage:(id)arg1 cornerRadius:(double)arg2 rectCornerType:(unsigned long long)arg3 backgroundColor:(id)arg4;
- (void)zy_cornerRadiusWithImage:(id)arg1 cornerRadius:(double)arg2 rectCornerType:(unsigned long long)arg3;
- (void)attachBorderWidth:(double)arg1 color:(id)arg2;
- (id)initWithCornerRadiusAdvance:(double)arg1 rectCornerType:(unsigned long long)arg2;
- (id)initWithRoundingRectImageView;
@end

