//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Tint)
- (id)darkenRect:(struct CGRect)arg1 withLevel:(double)arg2;
- (id)darkenWithLevel:(double)arg1 insets:(struct UIEdgeInsets)arg2;
- (id)darkenWithLevel:(double)arg1;
- (id)lightenRect:(struct CGRect)arg1 withLevel:(double)arg2;
- (id)lightenWithLevel:(double)arg1 insets:(struct UIEdgeInsets)arg2;
- (id)lightenWithLevel:(double)arg1;
- (id)tintedImageWithColor:(id)arg1 insets:(struct UIEdgeInsets)arg2 level:(double)arg3;
- (id)tintedImageWithColor:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (id)tintedImageWithColor:(id)arg1 rect:(struct CGRect)arg2 level:(double)arg3;
- (id)tintedImageWithColor:(id)arg1 rect:(struct CGRect)arg2;
- (id)tintedImageWithColor:(id)arg1 level:(double)arg2;
- (id)tintedImageWithColor:(id)arg1;
@end

