//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Sprite)
- (id)spritesWithSpriteSheetImage:(id)arg1 inRange:(struct _NSRange)arg2 spriteSize:(struct CGSize)arg3;
- (id)spritesWithSpriteSheetImage:(id)arg1 spriteSize:(struct CGSize)arg2;
@end

