//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (Letters)
- (id)imageSnapshotFromText:(id)arg1 backgroundColor:(id)arg2 circular:(_Bool)arg3 textAttributes:(id)arg4;
- (id)randomColor;
- (id)fontForFontName:(id)arg1;
- (void)setImageWithString:(id)arg1 color:(id)arg2 circular:(_Bool)arg3 textAttributes:(id)arg4;
- (void)setImageWithString:(id)arg1 color:(id)arg2 circular:(_Bool)arg3 fontName:(id)arg4;
- (void)setImageWithString:(id)arg1 color:(id)arg2 circular:(_Bool)arg3;
- (void)setImageWithString:(id)arg1 color:(id)arg2;
- (void)setImageWithString:(id)arg1;
@end

