//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (GeometryConversion)
- (struct CGRect)convertRectFromView:(struct CGRect)arg1;
- (struct CGPoint)convertPointFromView:(struct CGPoint)arg1;
- (struct CGRect)convertRectFromImage:(struct CGRect)arg1;
- (struct CGPoint)convertPointFromImage:(struct CGPoint)arg1;
@end

