//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSOperationQueue;

@interface UILabel (AutomaticWriting)
+ (void)load;
- (_Bool)deleteLastCharacter;
- (_Bool)deleteLastCharacters:(unsigned long long)arg1;
- (_Bool)isLastCharacter:(unsigned short)arg1;
- (_Bool)isLastCharacters:(id)arg1;
- (void)appendCharacters:(id)arg1;
- (void)appendCharacter:(unsigned short)arg1;
- (id)stringWithCharacters:(id)arg1;
- (id)stringWithCharacter:(unsigned short)arg1;
- (void)automaticWriting:(id)arg1 duration:(double)arg2 mode:(long long)arg3 character:(unsigned short)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setText:(id)arg1 automaticWritingAnimationWithDuration:(double)arg2 blinkingMode:(long long)arg3 blinkingCharacter:(unsigned short)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setText:(id)arg1 automaticWritingAnimationWithDuration:(double)arg2 blinkingMode:(long long)arg3 blinkingCharacter:(unsigned short)arg4;
- (void)setText:(id)arg1 automaticWritingAnimationWithDuration:(double)arg2 blinkingMode:(long long)arg3;
- (void)setText:(id)arg1 automaticWritingAnimationWithDuration:(double)arg2;
- (void)setText:(id)arg1 automaticWritingAnimationWithBlinkingMode:(long long)arg2;
- (void)setTextWithAutomaticWritingAnimation:(id)arg1;
@property(retain, nonatomic) NSOperationQueue *automaticWritingOperationQueue; // @dynamic automaticWritingOperationQueue;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @dynamic edgeInsets;
- (struct CGRect)automaticWritingTextRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2;
- (void)drawAutomaticWritingTextInRect:(struct CGRect)arg1;
@end

