//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIColor;

@interface UIMBorderView : UIView
{
    NSArray *_borderItems;
    unsigned long long _mBordertype;
    UIColor *_mColorBorder;
    double _mBorderWidth;
}

@property(nonatomic) double mBorderWidth; // @synthesize mBorderWidth=_mBorderWidth;
@property(retain, nonatomic) UIColor *mColorBorder; // @synthesize mColorBorder=_mColorBorder;
@property(nonatomic) unsigned long long mBordertype; // @synthesize mBordertype=_mBordertype;
@property(retain, nonatomic) NSArray *borderItems; // @synthesize borderItems=_borderItems;
- (void).cxx_destruct;
- (void)drawSampleLineRect:(struct CGRect)arg1;
- (void)drawEachLineRect:(struct CGRect)arg1 item:(id)arg2;
- (void)configCGContextRef:(struct CGContext *)arg1 item:(id)arg2;
- (void)drawEachLineRect:(struct CGRect)arg1;
- (id)itemFromType:(unsigned long long)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

