//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (Appear)
- (id)_imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (id)createBarButtonItems:(id)arg1;
- (void)addRightBarButtonItem:(id)arg1;
- (void)addLeftBarButtonItem:(id)arg1;
- (void)clearAllItem;
- (id)addItemWithTitle:(id)arg1 iconImage:(id)arg2 backgroundImage:(id)arg3 target:(id)arg4 action:(SEL)arg5 orientation:(long long)arg6;
- (void)setBarTitleView:(id)arg1;
- (void)setBarTitle:(id)arg1;
- (void)setBarBackgroundImage:(id)arg1;
- (void)setTitleColor:(id)arg1 font:(id)arg2;
- (void)setInteractivePopGestureRecognizerEnable:(_Bool)arg1;
- (void)setBarBackgroundColor:(id)arg1;
@end

