//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationItem.h"

@interface UINavigationItem (Lock)
- (void)lockLeftItem:(_Bool)arg1;
- (void)lockRightItem:(_Bool)arg1;
@end

