//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationItem.h"

@interface UINavigationItem (Margin)
+ (double)systemMargin;
+ (void)swizzle:(SEL)arg1;
+ (void)load;
- (void)swizzled_setRightBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (id)swizzled_rightBarButtonItems;
- (void)swizzled_setLeftBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (id)swizzled_leftBarButtonItems;
- (void)swizzled_setRightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (id)swizzled_rightBarButtonItem;
- (void)swizzled_setLeftBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (id)swizzled_leftBarButtonItem;
- (void)setOriginalRightBarButtonItems:(id)arg1;
- (id)originalRightBarButtonItems;
- (void)setOriginalLeftBarButtonItems:(id)arg1;
- (id)originalLeftBarButtonItems;
@property(nonatomic) double rightMargin;
@property(nonatomic) double leftMargin;
- (id)rightSpacerForItem:(id)arg1;
- (id)leftSpacerForItem:(id)arg1;
- (id)spacerForItem:(id)arg1 withMargin:(double)arg2;
@end

