//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface UIScrollView (PageNumber)
- (long long)pageNumber;
- (void)setPageNumber:(long long)arg1;
- (void)setPageNumber:(long long)arg1 animated:(_Bool)arg2;
- (_Bool)isFirstPage;
- (_Bool)isLastPage;
- (long long)totalPages;
@end

