//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface UIScrollView (Frame)
@property(nonatomic) double contentInsetLeft;
@property(nonatomic) double contentInsetBottom;
@property(nonatomic) double contentInsetRight;
@property(nonatomic) double contentInsetTop;
@property(nonatomic) double contentSizeHeight;
@property(nonatomic) double contentSizeWidth;
@property(nonatomic) double contentOffsetY;
@property(nonatomic) double contentOffsetX;
@end

