//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class UIView;

@interface UIScrollView (Amplification)
- (void)setup;
@property(retain, nonatomic) UIView *headerView;
@property(retain, nonatomic) UIView *bigView;
- (void)setBigView:(id)arg1 withHeaderView:(id)arg2;
@end

