//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (iOS7Style)
- (void)applyiOS7SettingsStyleGrouping:(id)arg1 forRowAtIndexPath:(id)arg2;
@end

