//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (CellStyle)
- (void)layer:(id)arg1 addLineUp:(_Bool)arg2 andLong:(_Bool)arg3 andColor:(struct CGColor *)arg4 andBounds:(struct CGRect)arg5 withLeftSpace:(double)arg6;
- (void)addLineforPlainCell:(id)arg1 forRowAtIndexPath:(id)arg2 withLeftSpace:(double)arg3 hasSectionLine:(_Bool)arg4 withLineColor:(id)arg5;
- (void)addLineforPlainCell:(id)arg1 forRowAtIndexPath:(id)arg2 withLeftSpace:(double)arg3 withLineColor:(id)arg4;
- (void)addLineforPlainCell:(id)arg1 forRowAtIndexPath:(id)arg2 withLeftSpace:(double)arg3;
- (void)addLineforPlainCell:(id)arg1 forRowAtIndexPath:(id)arg2 withLeftSpace:(double)arg3 hasSectionLine:(_Bool)arg4;
- (void)addRadiusforCell:(id)arg1 forRowAtIndexPath:(id)arg2;
@end

