//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (NIB)
+ (id)loadInstanceFromNibWithName:(id)arg1 owner:(id)arg2 bundle:(id)arg3;
+ (id)loadInstanceFromNibWithName:(id)arg1 owner:(id)arg2;
+ (id)loadInstanceFromNibWithName:(id)arg1;
+ (id)loadInstanceFromNib;
+ (id)loadNibNamed:(id)arg1 bundle:(id)arg2;
+ (id)loadNibNamed:(id)arg1;
+ (id)loadNib;
@end

