//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (KeyboardAnimation)
- (double)getDurationFromNotification:(id)arg1;
- (long long)getAnimationCurveFromNotification:(id)arg1;
- (struct CGRect)getKeyboardRectFromNotification:(id)arg1;
- (void)keyboardWillShowHide:(id)arg1 isShowing:(_Bool)arg2;
- (void)handleWillHideKeyboardNotification:(id)arg1;
- (void)handleWillShowKeyboardNotification:(id)arg1;
- (void)handleWillChageFrameKeyboardNotification:(id)arg1;
- (void)unsubscribeKeyboardFrameChanges;
- (void)unsubscribeKeyboard;
- (void)subscribeKeyboardWithBeforeAnimations:(CDUnknownBlockType)arg1 animations:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)subscribeKeyboardWithAnimations:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)subscribeKeyboardFrameChangesWithAnimations:(CDUnknownBlockType)arg1;
@end

