//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (TopBarMessage)
+ (void)setTopMessageDefaultApperance:(id)arg1;
- (void)dismissTopMessage;
- (void)showTopMessage:(id)arg1 topBarConfig:(id)arg2 mode:(int)arg3 dismissDelay:(float)arg4 withTapBlock:(CDUnknownBlockType)arg5;
- (void)showTopMessage:(id)arg1;
@end

