//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Shake)
- (void)_shake:(int)arg1 direction:(int)arg2 currentTimes:(int)arg3 withDelta:(double)arg4 speed:(double)arg5 shakeDirection:(long long)arg6 completion:(CDUnknownBlockType)arg7;
- (void)shake:(int)arg1 withDelta:(double)arg2 speed:(double)arg3 shakeDirection:(long long)arg4 completion:(CDUnknownBlockType)arg5;
- (void)shake:(int)arg1 withDelta:(double)arg2 speed:(double)arg3 shakeDirection:(long long)arg4;
- (void)shake:(int)arg1 withDelta:(double)arg2 speed:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (void)shake:(int)arg1 withDelta:(double)arg2 speed:(double)arg3;
- (void)shake:(int)arg1 withDelta:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)shake:(int)arg1 withDelta:(double)arg2;
- (void)shake;
@end

