//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (Alert)
- (void)showActionSheetWithTitle:(id)arg1 message:(id)arg2 options:(id)arg3 handlers:(id)arg4 presentFromView:(id)arg5;
- (void)showActionSheetWithTitle:(id)arg1 message:(id)arg2 options:(id)arg3 handlers:(id)arg4;
- (void)showActionSheetWithTitle:(id)arg1 message:(id)arg2 options:(id)arg3 handlers:(id)arg4 presentFromRect:(struct CGRect)arg5 inView:(id)arg6;
- (void)showAlertWithTitle:(id)arg1 andMessage:(id)arg2 andCancelButtonTitle:(id)arg3;
- (void)showAlertWithTitle:(id)arg1 andMessage:(id)arg2;
@end

