//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UIFont, UILabel;

@interface UIView (Badge)
@property(nonatomic) long long badgeMaximumBadgeNumber;
@property(nonatomic) double badgeRadius;
@property(nonatomic) struct CGPoint badgeCenterOffset;
@property(nonatomic) struct CGRect badgeFrame;
@property(nonatomic) unsigned long long aniType;
@property(retain, nonatomic) UIColor *badgeTextColor;
@property(retain, nonatomic) UIColor *badgeBgColor;
@property(retain, nonatomic) UIFont *badgeFont;
@property(retain, nonatomic) UILabel *badge;
- (void)removeAnimation;
- (void)beginAnimation;
- (void)adjustLabelWidth:(id)arg1;
- (void)badgeInit;
- (void)showNewBadge;
- (void)resetBadgeForRedDot;
- (void)showRedDotBadge;
- (void)showNumberBadgeWithValue:(long long)arg1;
- (void)resumeBadge;
- (void)clearBadge;
- (void)showNumberBadgeWithValue:(long long)arg1 animationType:(unsigned long long)arg2;
- (void)showBadgeWithStyle:(unsigned long long)arg1 value:(long long)arg2 animationType:(unsigned long long)arg3;
- (void)showBadge;
@end

