//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Animation)
- (_Bool)isBeingAnimated;
- (void)stopAnimation;
- (void)rotateToAngle:(double)arg1 duration:(double)arg2 direction:(unsigned long long)arg3 repeatCount:(unsigned long long)arg4 autoreverse:(_Bool)arg5;
- (void)flipWithDuration:(double)arg1 direction:(unsigned long long)arg2 repeatCount:(unsigned long long)arg3 autoreverse:(_Bool)arg4;
- (void)pulseToSize:(double)arg1 duration:(double)arg2 repeat:(_Bool)arg3;
- (void)applyMotionEffects;
- (void)shakeVertically;
- (void)shakeHorizontally;
@end

