//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (TopViewController)
+ (id)topViewController:(id)arg1;
- (void)presentViewControllerOnTopAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)topViewController;
@end

