//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface UIView (Radius)
- (void)setLayerShadow:(id)arg1 offset:(struct CGSize)arg2 radius:(double)arg3;
- (id)colorWithRGBHex:(unsigned int)arg1;
@property(nonatomic) _Bool masksToBounds;
@property(retain, nonatomic) UIColor *borderColor;
@property(nonatomic) long long borderWidth;
@property(nonatomic) long long cornerRadius;
@end

