//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Toast)
- (id)viewForMessage:(id)arg1 title:(id)arg2 image:(id)arg3;
- (struct CGSize)sizeForString:(id)arg1 font:(id)arg2 constrainedToSize:(struct CGSize)arg3 lineBreakMode:(long long)arg4;
- (struct CGPoint)centerPointForPosition:(id)arg1 withToast:(id)arg2;
- (void)hideToastActivity;
- (void)makeToastActivity:(id)arg1;
- (void)makeToastActivity;
- (void)handleToastTapped:(id)arg1;
- (void)toastTimerDidFinish:(id)arg1;
- (void)hideToast:(id)arg1;
- (void)showToast:(id)arg1 duration:(double)arg2 position:(id)arg3 tapCallback:(CDUnknownBlockType)arg4;
- (void)showToast:(id)arg1 duration:(double)arg2 position:(id)arg3;
- (void)showToast:(id)arg1;
- (void)makeToast:(id)arg1 duration:(double)arg2 position:(id)arg3 title:(id)arg4 image:(id)arg5;
- (void)makeToast:(id)arg1 duration:(double)arg2 position:(id)arg3 image:(id)arg4;
- (void)makeToast:(id)arg1 duration:(double)arg2 position:(id)arg3 title:(id)arg4;
- (void)makeToast:(id)arg1 duration:(double)arg2 position:(id)arg3;
- (void)makeToast:(id)arg1;
@end

