//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (RelativeLayout)
- (void)layoutRelativeOptions:(int)arg1 withRect:(struct CGRect)arg2 padding:(struct UIEdgeInsets)arg3;
- (void)layoutRelativeOptions:(int)arg1 withRect:(struct CGRect)arg2;
- (void)layoutRelativeOptions:(int)arg1 withView:(id)arg2 padding:(struct UIEdgeInsets)arg3;
- (void)layoutRelativeOptions:(int)arg1 withView:(id)arg2;
@end

