//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MJPopupBackgroundView;

@interface UIViewController (MJPopupViewController)
- (CDUnknownBlockType)dismissedCallback;
- (void)setDismissedCallback:(CDUnknownBlockType)arg1;
- (void)fadeViewOut:(id)arg1 sourceView:(id)arg2 overlayView:(id)arg3;
- (void)fadeViewIn:(id)arg1 sourceView:(id)arg2 overlayView:(id)arg3;
- (void)slideViewOut:(id)arg1 sourceView:(id)arg2 overlayView:(id)arg3 withAnimationType:(long long)arg4;
- (void)slideViewIn:(id)arg1 sourceView:(id)arg2 overlayView:(id)arg3 withAnimationType:(long long)arg4;
- (void)dismissPopupViewControllerWithanimation:(id)arg1;
- (id)topView;
- (void)presentPopupView:(id)arg1 animationType:(long long)arg2 dismissed:(CDUnknownBlockType)arg3;
- (void)presentPopupView:(id)arg1 animationType:(long long)arg2;
- (void)dismissPopupViewControllerWithanimationType:(long long)arg1;
- (void)presentPopupViewController:(id)arg1 animationType:(long long)arg2;
- (void)presentPopupViewController:(id)arg1 animationType:(long long)arg2 dismissed:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) MJPopupBackgroundView *mj_popupBackgroundView;
@property(retain, nonatomic) UIViewController *mj_popupViewController;
@end

