//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (Segues)
+ (void)load;
- (void)_prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)performSegueWithIdentifier:(id)arg1 prepareCallback:(CDUnknownBlockType)arg2;
@end

