//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface UIView (ViewPath)
- (id)stringFromBytes:(char *)arg1 length:(int)arg2;
@property(readonly, nonatomic) NSString *viewID;
@property(readonly, nonatomic) NSString *viewPath;
- (id)viewIndex;
- (id)viewName;
- (id)appendInfo;
- (id)containerViewControllerName;
- (_Bool)isRootView;
@end

