//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (WebStorage)
- (void)ip_clearWithStorage:(id)arg1;
- (void)ip_removeStringForKey:(id)arg1 storage:(id)arg2;
- (id)ip_stringForKey:(id)arg1 storage:(id)arg2;
- (void)ip_setString:(id)arg1 forKey:(id)arg2 storage:(id)arg3;
- (void)clearSessionStorage;
- (void)removeSessionStorageStringForKey:(id)arg1;
- (id)sessionStorageStringForKey:(id)arg1;
- (void)setSessionStorageString:(id)arg1 forKey:(id)arg2;
- (void)clearLocalStorage;
- (void)removeLocalStorageStringForKey:(id)arg1;
- (id)localStorageStringForKey:(id)arg1;
- (void)setLocalStorageString:(id)arg1 forKey:(id)arg2;
@end

