//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (JavaScript)
- (void)deleteNodeByTagName:(id)arg1;
- (void)deleteNodeByElementClass:(id)arg1;
- (void)deleteNodeByElementID:(id)arg1;
- (void)setFontSize:(int)arg1 withTag:(id)arg2;
- (void)setImgHeight:(int)arg1;
- (void)setImgWidth:(int)arg1;
- (void)addClickEventOnImg;
- (id)getOnClicks;
- (id)getImgs;
- (id)getTitle;
- (id)getCurrentURL;
- (int)nodeCountOfTag:(id)arg1;
@end

