//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (Style)
- (void)makeTransparentAndRemoveShadow;
- (void)makeTransparent;
- (void)showsVerticalScrollIndicator:(_Bool)arg1;
- (void)showsHorizontalScrollIndicator:(_Bool)arg1;
- (void)shadowViewHidden:(_Bool)arg1;
@end

