## Autogenerated from /Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm/tools/clang/test/Unit/lit.site.cfg.py.in
## Do not edit!

import sys

config.llvm_src_root = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm"
config.llvm_obj_root = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm_xcode"
config.llvm_tools_dir = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm_xcode/%(build_mode)s/bin"
config.llvm_libs_dir = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm_xcode/%(build_mode)s/lib"
config.llvm_build_mode = "%(build_mode)s"
config.clang_obj_root = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm_xcode/tools/clang"
config.enable_shared = 1
config.shlibdir = "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm_xcode/%(build_mode)s/lib"
config.target_triple = "x86_64-apple-darwin17.7.0"

# Support substitution of the tools_dir, libs_dirs, and build_mode with user
# parameters. This is used when we can't determine the tool dir at
# configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
    config.llvm_build_mode = config.llvm_build_mode % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

# Let the main config do the real work.
lit_config.load_config(config, "/Users/silence/Documents/Github/Me/iOS-Reverse/llvm/Source/llvm/tools/clang/test/Unit/lit.cfg.py")
